// <auto-generated />
using EF_Bus_Passengers_Test;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Bus_Passengers_Test.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240529222011_Create the bus and passengers tables")]
    partial class Createthebusandpassengerstables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Bus_Passengers_Test.Buss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BussName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfseats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("busses");
                });

            modelBuilder.Entity("EF_Bus_Passengers_Test.Passengers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BussId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BussId");

                    b.ToTable("passengers");
                });

            modelBuilder.Entity("EF_Bus_Passengers_Test.Passengers", b =>
                {
                    b.HasOne("EF_Bus_Passengers_Test.Buss", "Buss")
                        .WithMany("PassengersList")
                        .HasForeignKey("BussId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buss");
                });

            modelBuilder.Entity("EF_Bus_Passengers_Test.Buss", b =>
                {
                    b.Navigation("PassengersList");
                });
#pragma warning restore 612, 618
        }
    }
}
