// <auto-generated />
using EF_Bus_Passengers_Test;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Bus_Passengers_Test.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Bus_Passengers_Test.Buss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BussName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfseats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("busses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BussName = "The Malmö Mover",
                            NumberOfseats = 40
                        },
                        new
                        {
                            Id = 2,
                            BussName = "The Uppsala Uplift",
                            NumberOfseats = 50
                        });
                });

            modelBuilder.Entity("EF_Bus_Passengers_Test.Passengers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BussId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BussId");

                    b.ToTable("passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BussId = 1,
                            FirstName = "Saad",
                            LastName = "Sabah"
                        },
                        new
                        {
                            Id = 2,
                            BussId = 1,
                            FirstName = "Ali",
                            LastName = "Rami"
                        },
                        new
                        {
                            Id = 3,
                            BussId = 2,
                            FirstName = "Arai",
                            LastName = "Mani"
                        },
                        new
                        {
                            Id = 4,
                            BussId = 2,
                            FirstName = "Noor",
                            LastName = "Lother"
                        },
                        new
                        {
                            Id = 5,
                            BussId = 2,
                            FirstName = "Sara",
                            LastName = "Wriwei"
                        },
                        new
                        {
                            Id = 6,
                            BussId = 2,
                            FirstName = "Hamad",
                            LastName = "Mohamd"
                        },
                        new
                        {
                            Id = 7,
                            BussId = 2,
                            FirstName = "Solo",
                            LastName = "Hussain"
                        },
                        new
                        {
                            Id = 8,
                            BussId = 1,
                            FirstName = "Ziko",
                            LastName = "Fadi"
                        });
                });

            modelBuilder.Entity("EF_Bus_Passengers_Test.Passengers", b =>
                {
                    b.HasOne("EF_Bus_Passengers_Test.Buss", "Buss")
                        .WithMany("PassengersList")
                        .HasForeignKey("BussId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buss");
                });

            modelBuilder.Entity("EF_Bus_Passengers_Test.Buss", b =>
                {
                    b.Navigation("PassengersList");
                });
#pragma warning restore 612, 618
        }
    }
}
